apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: development-p49pb
  namespace: openshift-gitops
spec:
  clusterSelector:
    matchLabels:
      name: development-p49pb
