---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: lab-dummy
  namespace: openshift-gitops
spec:
  generators:
    - matrix:
        generators:
          - clusterDecisionResource:
              configMapRef: acm-placementrule
              name: dummy
              requeueAfterSeconds: 3600
          - git:
              repoURL: https://github.com/Vikaspogu/acm-demo.git
              revision: master
              directories:
                - path: managedclusters/lab/dummy/*
  template:
    metadata:
      name: 'lab-dummy-{{name}}-{{path.basename}}'
    spec:
      destination:
        server: "{{server}}"
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        path: "{{path}}"
        repoURL: "https://github.com/Vikaspogu/acm-demo.git"
        targetRevision: "master"
