---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: lab-development-p49pb
  namespace: openshift-gitops
spec:
  generators:
    - matrix:
        generators:
          - clusterDecisionResource:
              configMapRef: acm-placementrule
              name: development-p49pb
              requeueAfterSeconds: 3600
          - git:
              repoURL: https://github.com/Vikaspogu/acm-demo.git
              revision: main
              directories:
                - path: managedclusters/lab/development-p49pb/*
  template:
    metadata:
      name: 'lab-{{name}}-{{path.basename}}'
    spec:
      destination:
        server: "{{server}}"
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        path: "{{path}}"
        repoURL: "https://github.com/Vikaspogu/acm-demo.git"
        targetRevision: "main"
