---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: acm-install
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-50"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - git:
        repoURL: https://github.com/Vikaspogu/acm-demo.git
        revision: main
        directories:
          - path: hubcluster/acm/
  template:
    metadata:
      name: 'acm-{{path.basename}}'
    spec:
      destination:
        server: "https://kubernetes.default.svc"
      project: default
      syncPolicy: {}
      source:
        path: "{{path}}"
        repoURL: "https://github.com/Vikaspogu/acm-demo.git"
        targetRevision: "main"
