apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: lab-clusterset
  namespace: openshift-gitops
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: cluster.open-cluster-management.io/clusterset
          operator: In
          values:
          - lab-clusterset
